packages:
  - docs
  - packages/*
catalog:
  '@shikijs/twoslash': ^3.9.2
  '@shikijs/types': ^3.9.2
  '@shikijs/vitepress-twoslash': ^3.9.2
  shiki: ^3.9.2
  vite: ^7.1.2
  vitepress: ^2.0.0-alpha.11
