catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

packages:
  - docs
  - packages/*
catalog:
  '@antfu/eslint-config': ^6.7.3
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/ri': ^1.2.6
  '@iconify-json/simple-icons': ^1.2.63
  '@iconify-json/vscode-icons': ^1.2.37
  '@shikijs/types': ^3.20.0
  '@shikijs/vitepress-twoslash': ^3.20.0
  '@types/node': ^24.10.4
  '@unocss/eslint-plugin': ^66.5.10
  bumpp: ^10.3.2
  conventional-changelog-cli: ^5.0.0
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-plugin-format: ^1.1.0
  markdown-it-task-lists: ^2.1.1
  prompts: ^2.4.2
  sass: ^1.97.1
  shiki: ^3.20.0
  typedoc: ^0.28.15
  typedoc-plugin-markdown: ^4.9.0
  typedoc-vitepress-theme: ^1.1.2
  unbuild: ^3.6.1
  unocss: ^66.5.10
  unplugin-vue-components: ^30.0.0
  vite: ^7.3.0
  vite-plugin-vue-devtools: ^8.0.5
  vitepress: ^2.0.0-alpha.15
  vitepress-plugin-group-icons: ^1.6.5
  vue-tsc: ^3.2.1
  yargs: ^18.0.0
