packages:
  - docs
  - packages/*
catalog:
  '@shikijs/twoslash': ^3.13.0
  '@shikijs/types': ^3.13.0
  '@shikijs/vitepress-twoslash': ^3.13.0
  shiki: ^3.13.0
  vite: ^7.1.7
  vitepress: ^2.0.0-alpha.12
