/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoDocsProjectList: typeof import('./theme/components/demo/DemoDocsProjectList.vue')['default']
    DocsProjectCard: typeof import('./../../packages/docs/client/components/DocsProjectCard.vue')['default']
    DocsProjectList: typeof import('./../../packages/docs/client/components/DocsProjectList.vue')['default']
    GitHubBadge: typeof import('./theme/components/GitHubBadge.vue')['default']
    SiteLinkBadge: typeof import('./theme/components/SiteLinkBadge.vue')['default']
    StatusBadge: typeof import('./theme/components/StatusBadge.vue')['default']
  }
}
